"""Domain models for the Powerwave data intelligence layer.

These frozen dataclasses carry rule definitions and audit trails.
They are never stored inside DisturbanceRecord or SignalMetadata —
those remain locked data contracts.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class SourceFingerprint:
    """Lightweight descriptor of a recurring data source pattern.

    All fields are optional. A fingerprint scopes a MappingRule to a
    specific source: rules bound to a fingerprint only fire when that
    fingerprint matches the source being classified. Rules with
    source_fingerprint=None are global and apply to all sources.

    column_signature is a 16-hex-char SHA-256 prefix of the sorted,
    normalised column names — generated by build_fingerprint_from_columns.
    Do not set it manually.
    """

    vendor: str | None = None
    station: str | None = None
    export_type: str | None = None          # "comtrade" | "csv" | "excel"
    source_kind: str | None = None          # "scada_trend" | "fault_recorder" | …
    column_signature: str | None = None     # deterministic hex prefix


@dataclass(frozen=True, slots=True)
class MappingRule:
    """Reusable column → signal-type mapping rule.

    Stored in config/column_mapping_rules.yaml and loaded at runtime.
    When a rule matches, its confidence and signal_type replace whatever
    the built-in classifier inferred.

    match_type values:
      "exact"   — normalised column name must equal match_pattern exactly.
      "keyword" — match_pattern must appear as a substring of the name.
    """

    match_pattern: str                              # normalised (lower, stripped)
    match_type: str                                 # "exact" | "keyword"
    signal_type: str
    unit: str | None                                # None → keep classifier's unit
    display_group: str
    confidence: float                               # promoted confidence (0.0–1.0)
    confirmed_by_operator: bool                     # True → no user confirmation needed
    source_fingerprint: SourceFingerprint | None = None   # None = global rule
    notes: str | None = None


@dataclass(frozen=True, slots=True)
class TimestampRule:
    """Reusable timestamp format interpretation rule.

    Once an operator confirms how an ambiguous date column should be parsed,
    that interpretation is stored here for future reuse by similar sources.
    """

    source_pattern: str           # descriptive tag or fingerprint key (case-insensitive)
    date_format: str              # chosen format: "M/D/YYYY" | "D/M/YYYY" | "ISO8601" …
    ambiguous_resolution: str     # same value — records the resolution rationale
    confirmed_by_operator: bool
    notes: str | None = None


@dataclass(frozen=True, slots=True)
class ConfidencePromotion:
    """Immutable audit record of a confidence change from an intelligence rule.

    Returned alongside the updated ColumnClassification so callers have full
    traceability of what changed and why. Never stored in DisturbanceRecord.
    """

    original_confidence: float
    promoted_confidence: float
    original_inferred_from: str
    promoted_inferred_from: str       # always "persistent_mapping_rule"
    rule_match_pattern: str | None = None
